### PR TITLE
Quick fixes

### PR DESCRIPTION
**Pull request by lxingern**
Implemented some quick fixes after the demo today:
- Set 2 decimal places for prices
- Make photo in meal show page dynamic
- Flash message when meal is created

### CODE REVIEW

**Comment by barbayjuliette** [comment]
Show page: 
Screenshot 2022-11-17 at 18 11 18
The size of the image is not correct. 
The format should be the same for all pictures in show page, same as in index

**Comment by barbayjuliette** [comment]
Decimal and flash message okay

**Comment by lxingern** [comment]
Set dimensions of the image

**Comment by nxrara** [comment]
looks good

**Pull request merged**
